- README.md
- fdks/README.md
- fdks/fdk-go/README.md
- fdks/fdk-java/DataBinding.md
- fdks/fdk-java/ExtendingDataBinding.md
- fdks/fdk-java/FunctionConfiguration.md
- fdks/fdk-java/README.md
- fdks/fdk-node/README.md
- fdks/fdk-python/README.md
- fdks/fdk-ruby/README.md
Initial load of the Fn FDKs docs. If you approve, please go ahead and merge.
> Add Fn FDKs Docs

- examples/README.md
- examples/java/README.md
Here are the initial example docs. Only the Java example are linked in here. Do we want to pull in the actual source code into this repo?
> Initial example docs

- cli/how-to/create-init-image.md
- cli/ref/fn-init.md
Docs and how-to for init-images
> Init images

- fn/operate/logging.md
https://github.com/fnproject/fn/pull/1242
> update supported scheme list

- README.md
- fn/develop/pagination.md
- fn/operate/log-stores.md
A quick PR to add files and partial files from the Fn old doc files deletion list to the new docs repo. Added the files and links to them in the main landing page.
> Add files and partials from old file deletion list

- README.md
- fn/general/introduction.md
Updates to introduction for changes to Fn design. Will be used in other updates.
> Update introduction for Fn updates

- fn/develop/clients.md
Fixes the page to only point to Go for now.
> Remove all Fn sample clients except Go

- fn/operate/windows.md
closes https://github.com/fnproject/fn/issues/1268
> Update windows instructions with --privileged

- fn/develop/func-file.md
Add a list of current supported runtimes.
> Add list of runtimes to func.yaml docs

- fn/operate/runner_pools.md
> Updated runner deployment doc

- community/CONTRIBUTING.md
> quick link fix

- fn/develop/fdks.md
> Fix link in fdks.md file

- cli/README.md
- cli/ref/README.md
- cli/ref/fn-create-function.md
- cli/ref/fn-delete.md
- cli/ref/fn-get-config.md
- cli/ref/fn-get.md
- cli/ref/fn-init.md
- cli/ref/fn-invoke.md
- cli/ref/fn-list-config.md
- cli/ref/fn-list.md
- cli/ref/fn-unset.md
- cli/ref/fn-update-function.md
Updates all CL Ref materials for version 0.5.69.
> Fn CLI Ref update for 0.5.69 on 2019-04-03

- fn/operate/metrics.md
with https://github.com/fnproject/fn/pull/1472 this will be the required new url format (full url) for this
> update jaeger config

- fn/develop/configs.md
Removes route example and replaces with a function example.
> Fix config example

- fdks/fdk-java/examples/async-thumbnails/pom.xml
- fdks/fdk-java/examples/regex-query/pom.xml
> Bump Jackson in examples

- fn/develop/fn-format.md
this adds a few more details to color what's actually going on already in most of the FDKs, the doc I'm getting this from is a bit of a mess and I'm not sure if this is the complete thing yet here, but it's progress at least.
> update function contract doc

- cli/README.md
- cli/ref/README.md
> Update the version numbers for reference docs.

- fdks/fdk-java/examples/qr-code/README.md
- fdks/fdk-java/examples/qr-code/func.yaml
- fdks/fdk-java/examples/qr-code/pom.xml
- fdks/fdk-java/examples/qr-code/src/main/java/com/example/fn/QRGen.java
- fdks/fdk-java/examples/qr-code/src/test/java/com/example/fn/QRGenTest.java
Update this example to the latest Fn version
> Update Java FDK qr-code example to latest code

- cli/README.md
- cli/ref/README.md
- cli/ref/fn-build.md
- cli/ref/fn-push.md
> Updates for 0.5.86

- README.md
- fn/develop/fdks.md
Added links for updated FDK for Java examples.
> Added links for updated FDK for Java examples

- fdks/fdk-java/examples/qr-code/README.md
- fdks/fdk-java/examples/qr-code/example.html
- fdks/fdk-java/examples/qr-code/func.yaml
- fdks/fdk-java/examples/qr-code/src/main/java/com/example/fn/QRGen.java
A number of fixes. Removed Exception throwing statements that were crashing app. Used Optional to set default values instead. Updated for triggers. Set default values for images type and mime type.
> Updates to QR Code example and README

- fn/develop/func-file.md
Updating the func.yaml file according to: https://github.com/fnproject/docs/issues/106
> Updating func-file.md

- fdks/fdk-java/examples/async-thumbnails/README.md
- fdks/fdk-java/examples/async-thumbnails/func.yaml
- fdks/fdk-java/examples/async-thumbnails/pom.xml
- fdks/fdk-java/examples/async-thumbnails/setup/resize128/func.yaml
- fdks/fdk-java/examples/async-thumbnails/setup/resize256/func.yaml
- fdks/fdk-java/examples/async-thumbnails/setup/resize512/func.yaml
- fdks/fdk-java/examples/async-thumbnails/src/main/java/com/example/fn/ThumbnailsFunction.java
- fdks/fdk-java/examples/async-thumbnails/src/test/java/com/example/fn/ThumbnailsFunctionTest.java
Updates for Java 11. Added a warning related to Fn Flow.
> Update to Java Async Thumbnail Example

- fn/general/faq.md
Update the link to func.yaml. Remove the Question on scaling. The content was never written for that subject.
> Fix 2 broken links in faq.md

- fdks/fdk-java/README.md
- fdks/fdk-node/README.md
- fdks/fdk-ruby/README.md
- fn/develop/cloudevents.md
Changes to make FDK consistent. Function Development Kit for Language (FDK for Language).
> Updates for FDK for Language instances. Function Development Kit

- cli/README.md
- cli/ref/README.md
Update CLI Fn Version to 0.5.91
> Update CLI Fn Version to 0.5.91

- fdks/fdk-java/examples/async-thumbnails/pom.xml
- fdks/fdk-java/examples/regex-query/pom.xml
Made changes to regex and async thumbnails. Update Jackson version numbers as indicated.
> Make GitHub requested Security fixes.

- README.md
- fn/operate/variable-commands.md
Examples of all the commands used to manipulate variables.
> Fn Apps and Func Variable Command Reference

- README.md
> Update to simplify Docs TOC  

- README.md
- fn/develop/podman.md
Creates a markdown file documenting client support for podman.
> 02.15 Add note on Podman support
